# https://github.com/awslabs/serverless-application-model/blob/develop/versions/2016-10-31.md
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  Stage:
    Type: String
  ProjectName:
    Type: String

Globals:
  Function:
    Runtime: nodejs12.x
    Timeout: 180
    Tracing: Active

Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Sub ${Stage}

  Greeting:
    Type: AWS::Serverless::Function
    DependsOn: GreetingsTable
    Properties:
      Events:
        APIWithName:
          Type: Api
          Properties:
            Path: /hello/byname/{name}
            Method: get
            RestApiId:
              Ref: ApiGatewayApi
        APIAnonymous:
          Type: Api
          Properties:
            Path: /hello
            Method: get
            RestApiId:
              Ref: ApiGatewayApi
      Handler: hello.handler
      CodeUri: ./dist/hello
      Environment:
        Variables:
          ## With SimpleTable the reference would be easier, but we have less control
          # TABLE_NAME: !Ref SimpleTable
          TABLE_NAME: !Sub ${ProjectName}-greetings-${Stage}
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'dynamodb:DeleteItem'
                - 'dynamodb:GetItem'
                - 'dynamodb:PutItem'
                - 'dynamodb:UpdateItem'
              Resource: !GetAtt GreetingsTable.Arn

  # SimpleTable:
  #   TableName: !Sub ${ProjectName}-greetings-${Stage}
  #   Type: AWS::Serverless::SimpleTable
  #   Properties:
  #     PrimaryKey:
  #       Name: id
  #       Type: String

  GreetingsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${ProjectName}-greetings-${Stage}
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

Outputs:
  APIEndpoint:
    Description: 'API Endpoint'
    Value: !Sub 'https://${ApiGatewayApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}/hello/'
