# https://github.com/awslabs/serverless-application-model/blob/develop/versions/2016-10-31.md
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  Stage:
    Type: String
  ProjectName:
    Type: String

Globals:
  Function:
    Runtime: nodejs12.x
    Timeout: 180
    Tracing: Active

Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Sub ${Stage}

  Greeting:
    Type: AWS::Serverless::Function
    Properties:
      Events:
        APIWithName:
          Type: Api
          Properties:
            Path: /hello/byname/{name}
            Method: get
            RestApiId:
              Ref: ApiGatewayApi
        APIAnonymous:
          Type: Api
          Properties:
            Path: /hello
            Method: get
            RestApiId:
              Ref: ApiGatewayApi
      Handler: hello.handler
      CodeUri: ./dist/hello

  ExampleTable:
    TableName: !Sub ${ProjectName}-exampletable-${Stage}
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String

Outputs:
  ExampleTableArn:
    Description: Example Table ARN
    Value: !GetAtt ExampleTable.Arn
